-- Work shifts (one per shift per day, generated by scheduler)
CREATE TABLE work_shifts (
    id           BIGSERIAL PRIMARY KEY,
    shift_number SMALLINT   NOT NULL CHECK (shift_number IN (1,2,3)),
    shift_date   DATE       NOT NULL,
    start_time   TIMESTAMP  NOT NULL,
    end_time     TIMESTAMP  NOT NULL,
    UNIQUE (shift_number, shift_date)
);
CREATE INDEX idx_work_shifts_date ON work_shifts (shift_date);

-- Shift registrations (staff register for shifts, admin approves)
CREATE TABLE shift_registrations (
    id         BIGSERIAL PRIMARY KEY,
    shift_id   BIGINT      NOT NULL REFERENCES work_shifts(id) ON DELETE CASCADE,
    user_id    BIGINT      NOT NULL REFERENCES users(id),
    status     VARCHAR(20) NOT NULL DEFAULT 'REGISTERED' CHECK (status IN ('REGISTERED','APPROVED','CANCELLED')),
    created_at TIMESTAMP   NOT NULL DEFAULT NOW(),
    UNIQUE (shift_id, user_id)
);
CREATE INDEX idx_shift_reg_shift_id ON shift_registrations (shift_id);
CREATE INDEX idx_shift_reg_user_id  ON shift_registrations (user_id);

-- Overtime requests
CREATE TABLE overtime_requests (
    id                  BIGSERIAL PRIMARY KEY,
    requester_id        BIGINT      NOT NULL REFERENCES users(id),
    shift_id            BIGINT      NOT NULL REFERENCES work_shifts(id),
    reason              VARCHAR(500),
    ot_type             VARCHAR(20) NOT NULL CHECK (ot_type IN ('COVERING','EXTRA')),
    covering_user_id    BIGINT      REFERENCES users(id),
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','APPROVED','REJECTED')),
    telegram_message_id VARCHAR(100),
    created_at          TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP   NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_ot_req_requester ON overtime_requests (requester_id);

-- Attendance records
CREATE TABLE attendance_records (
    id                  BIGSERIAL PRIMARY KEY,
    user_id             BIGINT      NOT NULL REFERENCES users(id),
    shift_id            BIGINT      NOT NULL REFERENCES work_shifts(id),
    check_in_time       TIMESTAMP,
    check_out_time      TIMESTAMP,
    attend_status       VARCHAR(20) CHECK (attend_status IN ('ON_TIME','LATE','EARLY_LEAVE','ABSENT')),
    hours_worked        NUMERIC(5,2),
    is_overtime         BOOLEAN     NOT NULL DEFAULT FALSE,
    overtime_request_id BIGINT      REFERENCES overtime_requests(id),
    note                VARCHAR(500),
    created_at          TIMESTAMP   NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, shift_id)
);
CREATE INDEX idx_attendance_user_id  ON attendance_records (user_id);
CREATE INDEX idx_attendance_shift_id ON attendance_records (shift_id);
